# Copyright 2026 Kyudoka Research, H. Ismail <ismh@kyudoka.org>
# KR k-Length Computing Platform — Pin Assignments
# Digilent Genesys 2 — XC7K325T-2FFG900C
#
# Phase 1: UART + LEDs bring-up (no Ethernet)

# ==============================================================================
# Configuration
# ==============================================================================
set_property CFGBVS GND [current_design]
set_property CONFIG_VOLTAGE 1.8 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]

# ==============================================================================
# 200 MHz LVDS differential clock (AD12+/AD11-)
# ==============================================================================
set_property -dict {PACKAGE_PIN AD12 IOSTANDARD LVDS} [get_ports clk_200mhz_p]
set_property -dict {PACKAGE_PIN AD11 IOSTANDARD LVDS} [get_ports clk_200mhz_n]
create_clock -period 5.000 -name sys_clk [get_ports clk_200mhz_p]

# ==============================================================================
# Reset button — active-low (active-low on Genesys 2 "CPU Reset" button)
# ==============================================================================
set_property -dict {PACKAGE_PIN R19 IOSTANDARD LVCMOS33} [get_ports rstn_i]
set_false_path -from [get_ports rstn_i]

# ==============================================================================
# UART — Silicon Labs CP2103 (/dev/ttyUSBx)
# ==============================================================================
set_property -dict {PACKAGE_PIN Y20 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports uart_tx]
set_property -dict {PACKAGE_PIN Y23 IOSTANDARD LVCMOS33}           [get_ports uart_rx]
set_false_path -from [get_ports uart_rx]
set_false_path -to   [get_ports uart_tx]

# ==============================================================================
# LEDs (active high) — 8 user LEDs
# ==============================================================================
set_property -dict {PACKAGE_PIN T28  IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {led[0]}]
set_property -dict {PACKAGE_PIN V19  IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {led[1]}]
set_property -dict {PACKAGE_PIN U30  IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {led[2]}]
set_property -dict {PACKAGE_PIN U29  IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {led[3]}]
set_property -dict {PACKAGE_PIN V20  IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {led[4]}]
set_property -dict {PACKAGE_PIN V26  IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {led[5]}]
set_property -dict {PACKAGE_PIN W24  IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {led[6]}]
set_property -dict {PACKAGE_PIN W23  IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {led[7]}]

set_false_path -to [get_ports {led[*]}]

# ==============================================================================
# MMCM output clock constraints
# ==============================================================================
# Let Vivado auto-derive clocks generated by MMCM/PLL primitives.
# The MMCM takes the 200 MHz input and produces the system clock.
# No explicit create_generated_clock needed — Vivado infers from MMCM connectivity.
