name = "KLengthProofs"
version = "0.1.0"
defaultTargets = ["klengthproofs"]

[[lean_lib]]
name = "KLengthProofs"

[[lean_exe]]
name = "klengthproofs"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
version = "git#v4.28.0"
